# A setup with one name node, one data node,
# resource manager and one node manager.

services:
  namenode:
    image: apache/hadoop:3
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - "9870:9870"
    env_file:
      - "./config.env"
    environment:
      - ENSURE_NAMENODE_DIR="/tmp/hadoop-root/dfs/name"

  datanode:
    image: apache/hadoop:3
    command: ["hdfs", "datanode"]
    env_file:
      - "./config.env"

  resourcemanager:
    image: apache/hadoop:3
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
      - "8088:8088"
    env_file:
      - "./config.env"
    volumes:
      - "./test.sh:/opt/test.sh"

  nodemanager:
    image: apache/hadoop:3
    command: ["yarn", "nodemanager"]
    ports:
      - "8042:8042"
    env_file:
      - "./config.env"
